-----------------------------------------------------------

-- Notes:


-----------------------------------------------------------

USE [SEInventory]
GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_ItemComments_DELETE]
ON [app].[ItemComments] AFTER DELETE
AS

BEGIN 

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @ITEM_ID int
	DECLARE @COMMENT varchar(max)
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM DELETED
	SELECT @ITEM_ID = ITEM_ID FROM DELETED
	SELECT @COMMENT = COMMENT FROM DELETED
	SELECT @CREATED_BY = CREATED_BY FROM DELETED
	SELECT @CREATED_DATE = CREATED_DATE FROM DELETED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM DELETED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM DELETED

	UPDATE [hist].[Audit_ItemComments]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL
	AND ITEM_ID = @ITEM_ID
	AND ID = @ID;

	INSERT INTO [hist].[Audit_ItemComments] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ITEM_ID,ID,COMMENT,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (DATEADD(ms, 10,GETDATE()),GETDATE(),@ITEM_ID,@ID,@COMMENT,0,1,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_ItemComments_INSERT]
ON [app].[ItemComments] AFTER INSERT
AS

BEGIN 

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @ITEM_ID int
	DECLARE @COMMENT varchar(max)
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM INSERTED
	SELECT @ITEM_ID = ITEM_ID FROM INSERTED
	SELECT @COMMENT = COMMENT FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	INSERT INTO [hist].[Audit_ItemComments] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ITEM_ID,ID,COMMENT,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ITEM_ID,@ID,@COMMENT,1,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_ItemComments_UPDATE]
ON [app].[ItemComments] AFTER UPDATE
AS

BEGIN 

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @ITEM_ID int
	DECLARE @COMMENT varchar(max)
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM INSERTED
	SELECT @ITEM_ID = ITEM_ID FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE FROM INSERTED
	SELECT @COMMENT = COMMENT FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	UPDATE [hist].[Audit_ItemComments]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL 
	AND ITEM_ID = @ITEM_ID
	AND ID = @ID;
		
	INSERT INTO [hist].[Audit_ItemComments] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ITEM_ID,ID,COMMENT,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ITEM_ID,@ID,@COMMENT,0,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE);
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_Items_DELETE]
ON [app].[Items] AFTER DELETE
AS

BEGIN

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @STATUS varchar(10)
	DECLARE @TYPE varchar(15)
	DECLARE @BRAND varchar(100)
	DECLARE @SERIES varchar(100)
	DECLARE @NAME varchar(100) 
	DECLARE @DESCRIPTION varchar(250)
	DECLARE @FORMAT varchar(15)  
	DECLARE @SIZE varchar(10)
	DECLARE @YEAR int
	DECLARE @PHOTO varchar(max) 
	DECLARE @CREATED_BY varchar(100) 
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime
	
	SELECT @ID = ID FROM DELETED
	SELECT @STATUS = STATUS	FROM DELETED
	SELECT @TYPE = TYPE	FROM DELETED
	SELECT @BRAND = BRAND FROM DELETED
	SELECT @SERIES = SERIES FROM DELETED
	SELECT @NAME = NAME FROM DELETED
	SELECT @DESCRIPTION = DESCRIPTION FROM DELETED
	SELECT @FORMAT = FORMAT FROM DELETED
	SELECT @SIZE = SIZE	FROM DELETED
	SELECT @YEAR = YEAR	FROM DELETED
	SELECT @PHOTO = PHOTO FROM DELETED
	SELECT @CREATED_BY = CREATED_BY	FROM DELETED
	SELECT @CREATED_DATE = CREATED_DATE	FROM DELETED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM DELETED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM DELETED

	UPDATE [hist].[Audit_Items]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL
	AND ID = @ID;

	INSERT INTO [hist].[Audit_Items] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,STATUS,TYPE,BRAND,SERIES,NAME,DESCRIPTION,FORMAT,SIZE,YEAR,PHOTO,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (DATEADD(ms, 10,GETDATE()),GETDATE(),@ID,@STATUS,@TYPE,@BRAND,@SERIES,@NAME,@DESCRIPTION,@FORMAT,@SIZE,@YEAR,@PHOTO,0,1,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_Items_INSERT]
ON [app].[Items] AFTER INSERT
AS

BEGIN

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @STATUS varchar(10)
	DECLARE @TYPE varchar(15)
	DECLARE @BRAND varchar(100)
	DECLARE @SERIES varchar(100)
	DECLARE @NAME varchar(100) 
	DECLARE @DESCRIPTION varchar(250)
	DECLARE @FORMAT varchar(15)  
	DECLARE @SIZE varchar(10)
	DECLARE @YEAR int
	DECLARE @PHOTO varchar(max) 
	DECLARE @CREATED_BY varchar(100) 
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM INSERTED
	SELECT @STATUS = STATUS	FROM INSERTED
	SELECT @TYPE = TYPE	FROM INSERTED
	SELECT @BRAND = BRAND FROM INSERTED
	SELECT @SERIES = SERIES FROM INSERTED
	SELECT @NAME = NAME FROM INSERTED
	SELECT @DESCRIPTION = DESCRIPTION FROM INSERTED
	SELECT @FORMAT = FORMAT FROM INSERTED
	SELECT @SIZE = SIZE	FROM INSERTED
	SELECT @YEAR = YEAR	FROM INSERTED
	SELECT @PHOTO = PHOTO FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY	FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE	FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	INSERT INTO [hist].[Audit_Items] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,STATUS,TYPE,BRAND,SERIES,NAME,DESCRIPTION,FORMAT,SIZE,YEAR,PHOTO,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ID,@STATUS,@TYPE,@BRAND,@SERIES,@NAME,@DESCRIPTION,@FORMAT,@SIZE,@YEAR,@PHOTO,1,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-------------------------------------------------------------

CREATE OR ALTER TRIGGER [app].[Trigger_Items_UPDATE]
ON [app].[Items] AFTER UPDATE
AS

BEGIN

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @STATUS varchar(10)
	DECLARE @TYPE varchar(15)
	DECLARE @BRAND int
	DECLARE @SERIES int
	DECLARE @NAME varchar(100) 
	DECLARE @DESCRIPTION varchar(250)
	DECLARE @FORMAT varchar(15)  
	DECLARE @SIZE varchar(10)
	DECLARE @YEAR int
	DECLARE @PHOTO varchar(max)  
	DECLARE @CREATED_BY varchar(100) 
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = ID FROM INSERTED
	SELECT @STATUS = STATUS	FROM INSERTED
	SELECT @TYPE = TYPE	FROM INSERTED
	SELECT @BRAND = BRAND FROM INSERTED
	SELECT @SERIES = SERIES FROM INSERTED
	SELECT @NAME = NAME FROM INSERTED
	SELECT @DESCRIPTION = DESCRIPTION FROM INSERTED
	SELECT @FORMAT = FORMAT FROM INSERTED
	SELECT @SIZE = SIZE	FROM INSERTED
	SELECT @YEAR = YEAR	FROM INSERTED
	SELECT @PHOTO = PHOTO FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY	FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE	FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	UPDATE [hist].[Audit_Items]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL 
	AND ID = @ID;
		
	INSERT INTO [hist].[Audit_Items] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,STATUS,TYPE,BRAND,SERIES,NAME,DESCRIPTION,FORMAT,SIZE,YEAR,PHOTO,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ID,@STATUS,@TYPE,@BRAND,@SERIES,@NAME,@DESCRIPTION,@FORMAT,@SIZE,@YEAR,@PHOTO,0,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE);
END

GO

-----------------------------------------------------------
