-----------------------------------------------------------

-- Notes:


-----------------------------------------------------------

USE [StarryEdenUser]
GO

-----------------------------------------------------------

CREATE TRIGGER [app].[Trigger_Users_DELETE]
ON [app].[Users] AFTER DELETE
AS

BEGIN 

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @NAME varchar(250)
	DECLARE @PASS_SALT varchar(250)
	DECLARE @PASS_HASH varchar(250)
	DECLARE @ROLE_ID int
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = [ID] FROM DELETED
	SELECT @NAME = [NAME] FROM DELETED
	SELECT @PASS_SALT = PASS_SALT FROM DELETED
	SELECT @PASS_HASH = PASS_HASH FROM DELETED
	SELECT @ROLE_ID = ROLE_ID FROM DELETED
	SELECT @CREATED_BY = CREATED_BY FROM DELETED
	SELECT @CREATED_DATE = CREATED_DATE FROM DELETED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM DELETED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM DELETED

	UPDATE [hist].[Audit_Users]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL
	AND [ID] = @ID;

	INSERT INTO [hist].[Audit_Users] (EFFECTIVE_DATE,INEFFECTIVE_DATE,[ID],[NAME],PASS_SALT,PASS_HASH,ROLE_ID,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (DATEADD(ms, 10,GETDATE()),GETDATE(),@ID,@NAME,@PASS_SALT,@PASS_HASH,@ROLE_ID,0,1,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE TRIGGER [app].[Trigger_Users_INSERT]
ON [app].[Users] AFTER INSERT
AS

BEGIN 

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @NAME varchar(250)
	DECLARE @PASS_SALT varchar(250)
	DECLARE @PASS_HASH varchar(250)
	DECLARE @ROLE_ID int
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = [ID] FROM INSERTED
	SELECT @NAME = [NAME] FROM INSERTED
	SELECT @PASS_SALT = PASS_SALT FROM INSERTED
	SELECT @PASS_HASH = PASS_HASH FROM INSERTED
	SELECT @ROLE_ID = ROLE_ID FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	INSERT INTO [hist].[Audit_Users] (EFFECTIVE_DATE,INEFFECTIVE_DATE,ID,[NAME],PASS_SALT,PASS_HASH,ROLE_ID,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ID,@NAME,@PASS_SALT,@PASS_HASH,@ROLE_ID,1,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE); 		  
END

GO

-----------------------------------------------------------

CREATE TRIGGER [app].[Trigger_Users_UPDATE]
ON [app].[Users] AFTER UPDATE
AS

BEGIN 

	SET NOCOUNT ON;

	DECLARE @ID int
	DECLARE @NAME varchar(250)
	DECLARE @PASS_SALT varchar(250)
	DECLARE @PASS_HASH varchar(250)
	DECLARE @ROLE_ID int
	DECLARE @CREATED_BY varchar(100)
	DECLARE @CREATED_DATE datetime
	DECLARE @LAST_MODIFIED_BY varchar(100)
	DECLARE @LAST_MODIFIED_DATE datetime

	SELECT @ID = [ID] FROM INSERTED
	SELECT @NAME = [NAME] FROM INSERTED
	SELECT @PASS_SALT = PASS_SALT FROM INSERTED
	SELECT @PASS_HASH = PASS_HASH FROM INSERTED
	SELECT @ROLE_ID = ROLE_ID FROM INSERTED
	SELECT @CREATED_BY = CREATED_BY FROM INSERTED
	SELECT @CREATED_DATE = CREATED_DATE FROM INSERTED
	SELECT @LAST_MODIFIED_BY = LAST_MODIFIED_BY FROM INSERTED
	SELECT @LAST_MODIFIED_DATE = LAST_MODIFIED_DATE FROM INSERTED

	UPDATE [hist].[Audit_Users]
	SET INEFFECTIVE_DATE = GETDATE()
	WHERE INEFFECTIVE_DATE IS NULL 
	AND [ID] = @ID;
		
	INSERT INTO [hist].[Audit_Users] (EFFECTIVE_DATE,INEFFECTIVE_DATE,[ID],[NAME],PASS_SALT,PASS_HASH,ROLE_ID,ADDED,DELETED,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) 
	VALUES (GETDATE(),NULL,@ID,@NAME,@PASS_SALT,@PASS_HASH,@ROLE_ID,0,0,@CREATED_BY,@CREATED_DATE,@LAST_MODIFIED_BY,@LAST_MODIFIED_DATE);
END

GO

-----------------------------------------------------------